### ISSUE TITLE
No way to leave :relay-types unspecified in 0.6.19.

### ISSUE THREAD

**Issue by kamituel** [matthiasn/systems-toolbox-sente#11]
In `0.6.19` a [change has been made](https://github.com/matthiasn/systems-toolbox-sente/blob/9817d17c88ac7503eea664467ddf8f4174c07200/src/cljs/matthiasn/systems_toolbox_sente/client.cljs#L135) that effectively prohibits application from not specifying `:relay-types`.

Here's the simplified, commented code:

```clojure
(if-let [;; Will always be a non-empty set, see comments below.
            msg-types (set/union
                         ;; If :relay-types is nil, it'll be #{}, not nil,
                         ;; because (set nil) evaluates to #{}.
                         (set (:relay-types cfg))
                         ;; Always non-empty set.
                         #{…})]
            ;; Always returned.
            {:handler-map (zipmap msg-types (repeat all-msgs-handler))}
            ;; Never returned!
            {:all-msgs-handler all-msgs-handler})
```

---

By the way - why is `:relay-types` going to be required in the future (there's a deprecation notice when is not used)?

Currently, there are two places where command types that are going to be sent over sente component can be specified:
- in the switchboard routing, in `:cmd/route`, when `:only` is specified.
- in `:relay-types`

And I prefer the former:

```clojure
[:cmd/init-cmp #{(sente/cmp-map :frontend/sente {… …})}]
…
;; I immediately know which component sends which command over web sockets.
[:cmd/route :from :frontend/cmp-1 :to :frontend/sente :only [:users/list]]
[:cmd/route :from :frontend/cmp-2 :to :frontend/sente :only [:orders/list]]
[:cmd/route :from :frontend/cmp-3 :to :frontend/sente :only [:emails/list :emails/send]]
```

vs:

```clojure
;; I only know which commands are sent over web sockets, but have no idea
;; which component originates each.
[:cmd/init-cmp #{(sente/cmp-map :frontend/sente {:relay-types [:users/list
                                                               :orders/list
                                                               :emails/list
                                                               :emails/send]}}})}]
…
[:cmd/route :from :frontend/cmp-1 :to :frontend/sente]
[:cmd/route :from :frontend/cmp-2 :to :frontend/sente]
[:cmd/route :from :frontend/cmp-3 :to :frontend/sente]
```

Of course both can be mixed, i.e. both `:cmd/route` with `:only`, and `:relay-types` can be used, but than it's a duplication that's just annoying to maintain.

So, could we un-deprecate not using `:relay-types`? I can fix the bug, so in one go I could also remove that deprecation notice :)

**Comment by matthiasn** [comment]
Sure, that makes sense. I don't remember what in particular made me change this, but looking at your example, it really does look better and more obvious to specify the message type with the actual route. I think I may actually change it in my projects, too. Currently I was using the `:relay-types` only. Cheers

**Comment by matthiasn** [comment]
reverted in latest version
