### ISSUE TITLE
Overriding default routes

### ISSUE THREAD

**Issue by BartAdv** [matthiasn/systems-toolbox-sente#5]
Recently we've had (rather strange) requirement - we've had to disable the sente endpoints for particular configuration, and we didn't want to disable systems-toolbox-sente as a whole. The simplest solution seemed to just override `/chsk` routes to just reply `404`, but it was impossible - simply because user routes come after default routes. I've changed this order in a local fork (https://github.com/BartAdv/systems-toolbox-sente/commit/5f35cf4b78a10b0f42b150104cccce1fdd4c4d80), as I'm not sure whether it makes sense to go to the mainline. This issue is created to check whether it would be reasonable default.

**Comment by matthiasn** [comment]
Hey Bartosz, yeah why not, I'm a fan of being able to override defaults. This makes more sense than the current behavior. Please feel free to submit a PR for this fix. Cheers, M

**Comment by BartAdv** [comment]
Thanks! Prepared two PRs for this (one for 0.5.x, the other for master): #6, #7

**Comment by matthiasn** [comment]
merged and published, cheers
